<div class="container h-100">  
        <div class="row h-100 justify-content-center align-items-center">
          <div class="col-sm-5">
            <div class="card bg-danger border-dark">
                <div class="card-header">
                    <img class="img-size2 mr-5" src="img/arcanine.png"><strong>Lista de pontos</strong>
                </div>
                <br>
                <div class="alert alert-danger" role="alert">
                    <h4 class="alert-heading">Atenção!</h4>
                    <p>As brokes mostradas aqui são feitas por players, sempre confira a broke na nossa calculadora.</p>
                    <p>Os pontos mostrados são o total, reduza os 10% e arredonde como preferir.</p>
                    <hr>
                    <p class="mb-0">Caso deseje adicionar uma broke a nossa lista, entre em contato in-game ou pelo email: broke@shbroke.com.br</p>
                    </div>
                <br>
                <div class="form-group ml-4">
                <form method="GET">
                    <div class="form-group row ml-4">
                    <label for="pokemon">Selecione um Pokémon</label>
                    </div>
                    <div class="col-sm-12">
                    <select class="form-control" name="pokemon" id="pokemon">
                        <option value="">-- Selecione --</option>
                        
                        <?php
                            foreach ($this->lista as $lista) {        
                        ?>
                            <option value="<?php echo $lista["id"];?>"><?php echo $lista["id"].' - '.$lista["nome"];?></option>

                            <?php
                                };
                            ?>
                        
                    </select> 
                    </div><br>
                    <div class="col-sm-12">
                    <input class="btn btn-success" type="submit" value="Busca">
                    
                    </div>
                </form>
                </div>

                <?php
                if (isset($_GET['pokemon'])){

                    if (count($this->poke) > 0){
                        echo '<button type="button" class="btn btn-success border-top rounded-0" data-toggle="modal" data-target="#modalDetails">'.$this->poke[0]['nome'] .'</button>';
                    }else {
                        echo '<button type="button" class="btn btn-danger border-top rounded-0">Selecione um Pokémon da Lista.</button>';
                    }
                }
                ?>
                
                <!-- Modal -->
                <div class="modal fade" id="modalDetails" tabindex="-1" role="dialog" aria-labelledby="modalDetailsLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="modalDetailsLabel">Detalhes do Pokémon</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <?php
                            echo '<table class="table table-sm text-center">
                            <thead class="thead-secondary table-secondary">
                                <tr>
                                    <th scole="col">#</th>
                                    <th scope="col"></th>
                                    <th scope="col">Num. Dex</th>
                                    <th scope="col">Nome</th>
                                    <th scope="col">Broke</th>
                                    
                                    </tr>
                            </thead>
                            <tbody class="table-striped">
                                <tr>
                                    <th scope="col" class="pt-4">#</th>
                                    <td><img src="'.$this->poke[0]['imagem'].'"></td>
                                    <td class="pt-4">' .$this->poke[0]['id']. '</td>
                                    <td class="pt-4">' .$this->poke[0]['nome'] . '</td>
                                    <td class="pt-4">' .$this->poke[0]['pontos'] . ' pontos</td>
                                </tr>
                            </tbody>
                        </table>'
                        ?>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                    </div>
                    </div>
                </div>
                </div>
                
            </div>
          </div>              
        </div> 