<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Calculadora de Broke PSOUL</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="styles/styles.css">

    <script src="js/scripts.js"></script>
    

    <script src="https://kit.fontawesome.com/b93f9b3c01.js" crossorigin="anonymous"></script>
</head>
<body>

      <nav class="navbar pb-0 navbar-secondary bg-danger fixed-top">
        <ul class="nav nav-pills nav-fill center justify-content-center mx-auto p-2 pb-3">
            <li class="nav-item m-1">
                <a class="nav-link btn btn-secondary" href="/">Calcular</a>
            </li>
            <li class="nav-item m-1">
                <a class="nav-link btn btn-secondary" href="/montar">Montar</a>
            </li>
            <li class="nav-item m-1">
                <a class="nav-link btn btn-secondary" href="/lista">Lista</a>
            </li>
          </ul>
    </nav>

    <?php
        $this->content();
    ?>

    <footer class="page-footer bg-secondary font-small fixed-bottom">

        
        <div class="footer-copyright text-center py-3">Calculadora e lista de broke PSOUL v2 © 2022 Copyright:
        <a class="badge badge-pill badge-secondary" href="https://psoul.com.br/player/30406"> Gkill</a>
        <a href="https://github.com/pcezars"><i class="fa-brands fa-github"></i></a>
        <a href="https://www.linkedin.com/in/pcezars/"><i class="fa-brands fa-linkedin"></i></a>
        </div>
        
    
    </footer>
    
</body>
</html>